sync:
  image: n3llyb0y/wait
  links:
    - call-logd
    - swagger-validator
  environment:
    PORTS: "9298 8080"
    TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

call-logd:
  image: wazo-call-logd-test
  volumes:
    - "../../..:/usr/src/wazo-call-logd"
    - "./etc/wazo-call-logd:/etc/wazo-call-logd"
    # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/usr/local/lib/python3.4/site-packages/xivo"
    # - "${LOCAL_GIT_REPOS}/xivo-dao/xivo_dao:/usr/local/lib/python3.4/site-packages/xivo_dao"
    # - "${LOCAL_GIT_REPOS}/xivo-bus/xivo_bus:/usr/local/lib/python3.4/site-packages/xivo_bus"
  ports:
    - "9298:9298"
  environment:
    XIVO_UUID: "08c56466-8f29-45c7-9856-92bf1ba89b92"

swagger-validator:
  image: swaggerapi/swagger-validator
  ports:
    - "8080"
  links:
    - call-logd
