version: '3'
services:
  sync:
    image: wazopbx/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  auth:
    image: wazopbx/wazo-auth-mock
    ports:
      - "9497"
    volumes:
      - "./ssl:/usr/local/share/ssl"

  call-logd:
    image: wazo-call-logd-test
    volumes:
      - "../..:/usr/src/wazo-call-logd"
      - "./ssl:/usr/local/share/ssl"
      - "./etc/wazo-call-logd/key.yml:/etc/wazo-call-logd/key.yml"
      - "./etc/wazo-call-logd/conf.d/auth.yml:/etc/wazo-call-logd/conf.d/50-auth.yml"
      - "./etc/wazo-call-logd/conf.d/db_uri.yml:/etc/wazo-call-logd/conf.d/50-db_uri.yml"
      - "./etc/wazo-call-logd/conf.d/bus.yml:/etc/wazo-call-logd/conf.d/50-bus.yml"
      - "./etc/wazo-call-logd/conf.d/confd.yml:/etc/wazo-call-logd/conf.d/50-confd.yml"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/usr/local/lib/python3.5/site-packages/xivo"
      # - "${LOCAL_GIT_REPOS}/xivo-dao/xivo_dao:/usr/local/lib/python3.5/site-packages/xivo_dao"
      # - "${LOCAL_GIT_REPOS}/xivo-bus/xivo_bus:/usr/local/lib/python3.5/site-packages/xivo_bus"
    ports:
      - "9298"
    environment:
      XIVO_UUID: "08c56466-8f29-45c7-9856-92bf1ba89b92"

  confd:
    image: wazopbx/xivo-confd-mock
    ports:
      - "9486"
    volumes:
      - "./ssl:/usr/local/share/ssl"

  postgres:
    image: wazopbx/postgres-test
    ports:
      - "5432"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
